// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGqM7jyUA6QVxPeSi7C5El8Y6vHNFUvc',
    appId: '1:597563194177:web:082290cbaabe6db1487fc0',
    messagingSenderId: '597563194177',
    projectId: 'emart24-6bc24',
    authDomain: 'emart24-6bc24.firebaseapp.com',
    storageBucket: 'emart24-6bc24.firebasestorage.app',
    measurementId: 'G-6Y5DGJ4HLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzeQvdgt1tX-rGtNGhk25r7Sk6sMZVIQ0',
    appId: '1:597563194177:android:652defe33cc2e9eb487fc0',
    messagingSenderId: '597563194177',
    projectId: 'emart24-6bc24',
    storageBucket: 'emart24-6bc24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYt0DTv6m24oTfcM3KBvasX3UAGyDuugY',
    appId: '1:597563194177:ios:ee47a8d2f7f12242487fc0',
    messagingSenderId: '597563194177',
    projectId: 'emart24-6bc24',
    storageBucket: 'emart24-6bc24.firebasestorage.app',
    iosBundleId: 'com.kongchansila.EMART24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYt0DTv6m24oTfcM3KBvasX3UAGyDuugY',
    appId: '1:597563194177:ios:ee47a8d2f7f12242487fc0',
    messagingSenderId: '597563194177',
    projectId: 'emart24-6bc24',
    storageBucket: 'emart24-6bc24.firebasestorage.app',
    iosBundleId: 'com.kongchansila.EMART24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvGqM7jyUA6QVxPeSi7C5El8Y6vHNFUvc',
    appId: '1:597563194177:web:c45cea430c41fc3f487fc0',
    messagingSenderId: '597563194177',
    projectId: 'emart24-6bc24',
    authDomain: 'emart24-6bc24.firebaseapp.com',
    storageBucket: 'emart24-6bc24.firebasestorage.app',
    measurementId: 'G-8VG8SVP0WH',
  );
}
